ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyLiDAR
    frame_id: laser_frame
    ignore_array: ""
    baudrate: 230400
    # baudrate: 115200
    lidar_type: 1
    device_type: 0
    sample_rate: 4
    intensity_bit: 10
    abnormal_check_count: 4
    fixed_resolution: true
    reversion: true
    inverted: true
    auto_reconnect: true
    isSingleChannel: false
    intensity: true
    support_motor_dtr: false
<<<<<<< HEAD
    angle_max: 90.0                  ## 180.00
    angle_min: -90.0                 ## -180.00
=======
    angle_max: 120.0                  ## 180.00
    angle_min: -120.0                 ## -180.00
>>>>>>> 3c22981dce932cfa6a1863dd8907db256d3f0fd3
    range_max: 16.0
    range_min: 0.1
    frequency: 10.0
    invalid_range_is_inf: false
